@Library('my-test-lib')_
pipeline {
    agent any
    environment {
        ENV_TEST_VAR = '1.3.0'
    }
    parameters {
        string(name: 'BRANCH_NAME', defaultValue: 'main', description: 'Branch Name')
        choice(name: 'PACKAGES', choices: ['test', 'test2', 'test3'], description: 'Select package to build')
    }
    stages {
        stage('Depedencies') {
            steps {
                sh 'yarn version'
            }
        }
        
        stage('Custom Lib') {
            steps {
                echo 'Hello '
                myLibFile 'Ganesh'
            }
        }
        
        stage('Tests') {
            when {
                expression {
                    params.SKIP_TESTS != true
                }
            }
            steps {
                echo 'Running tests'
            }
        }

        stage('Build') {
            steps {
                echo 'Running build...'
                echo "Building version ${ENV_TEST_VAR}"
                echo "BRANCH_NAME = ${params.BRANCH_NAME}"
                echo "package to deploy = ${params.PACKAGES}"
            }
        }
        
        stage('Artifact') {
            steps {
                echo 'Uploading to Artifact'
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying...'
            }
        }
    }
    post {
        always {
            echo 'post build always'
        }
        success {
            echo 'post build success'
        }
        failure {
            echo 'post build failure'
        }
    }
}
