name: ABC CI

  on: 
    push: 
      branches:
        - main
    pull_request:
      branches: 
        - main
  jobs:
    test_pull_request:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version:12
            cache: 'yarn'
        - run: yarn install
        - run: yarn test
        - run: yarn run build

